# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    - &OrdererOrg
        Name: OrdererOrg

        ID: OrdererMSP

        MSPDir: /root/ldsun/k/certs/crypto-config/ordererOrganizations/swan.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &Org1
        Name: Org1MSP

        ID: Org1MSP

        MSPDir: /root/ldsun/k/certs/crypto-config/peerOrganizations/org1.swan.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org1MSP.admin')"

        AnchorPeers:
            - Host: peer0.org1.swan.com
              Port: 7051

    - &Org2
        Name: Org2MSP

        ID: Org2MSP

        MSPDir: /root/ldsun/k/certs/crypto-config/peerOrganizations/org2.swan.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org2MSP.admin')"

        AnchorPeers:
            - Host: peer0.org2.swan.com
              Port: 9051

Capabilities:

    Channel: &ChannelCapabilities

        V1_4_2: true

        V1_3: false

        V1_1: false

    Orderer: &OrdererCapabilities

        V1_4_2: true

        V1_1: false

    Application: &ApplicationCapabilities

        V1_4_2: true

        V1_3: false

        V1_2: false

        V1_1: false

Application: &ApplicationDefaults

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    EtcdRaft:
        Consenters:
            - Host: orderer1.swan.com
              Port: 7050
              ClientTLSCert: /root/ldsun/k/certs/crypto-config/ordererOrganizations/swan.com/orderers/orderer1.swan.com/tls/server.crt
              ServerTLSCert: /root/ldsun/k/certs/crypto-config/ordererOrganizations/swan.com/orderers/orderer1.swan.com/tls/server.crt
            - Host: orderer2.swan.com
              Port: 8050
              ClientTLSCert: /root/ldsun/k/certs/crypto-config/ordererOrganizations/swan.com/orderers/orderer2.swan.com/tls/server.crt
              ServerTLSCert: /root/ldsun/k/certs/crypto-config/ordererOrganizations/swan.com/orderers/orderer2.swan.com/tls/server.crt
            - Host: orderer3.swan.com
              Port: 9050
              ClientTLSCert: /root/ldsun/k/certs/crypto-config/ordererOrganizations/swan.com/orderers/orderer3.swan.com/tls/server.crt
              ServerTLSCert: /root/ldsun/k/certs/crypto-config/ordererOrganizations/swan.com/orderers/orderer3.swan.com/tls/server.crt
            - Host: orderer4.swan.com
              Port: 10050
              ClientTLSCert: /root/ldsun/k/certs/crypto-config/ordererOrganizations/swan.com/orderers/orderer4.swan.com/tls/server.crt
              ServerTLSCert: /root/ldsun/k/certs/crypto-config/ordererOrganizations/swan.com/orderers/orderer4.swan.com/tls/server.crt
            - Host: orderer5.swan.com
              Port: 11050
              ClientTLSCert: /root/ldsun/k/certs/crypto-config/ordererOrganizations/swan.com/orderers/orderer5.swan.com/tls/server.crt
              ServerTLSCert: /root/ldsun/k/certs/crypto-config/ordererOrganizations/swan.com/orderers/orderer5.swan.com/tls/server.crt

    Addresses:
        - orderer1.swan.com:7050
        - orderer2.swan.com:8050
        - orderer3.swan.com:9050
        - orderer4.swan.com:10050
        - orderer5.swan.com:11050

    BatchTimeout: 1s

    BatchSize:

        MaxMessageCount: 500

        AbsoluteMaxBytes: 99 MB

        PreferredMaxBytes: 4096 KB

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    SWANMultiNodeEtcdRaft:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - <<: *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1
                    - *Org2

    TwoOrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
            Capabilities:
                <<: *ApplicationCapabilities

    ThreeOrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
            Capabilities:
                <<: *ApplicationCapabilities
