# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:

  - Name: Orderer
    Domain: swan.com

    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5

PeerOrgs:

  - Name: Org1
    Domain: org1.swan.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 4

  - Name: Org2
    Domain: org2.swan.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 4
